blank_issues_enabled: false
contact_links:
    - name: Bug reports
      url: https://github.com/ente-io/ente/discussions
      about: https://github.com/ente-io/ente/issues/new/choose
    - name: Feature requests and questions
      url: https://github.com/ente-io/ente/discussions
      about: Please use Discussions in our new repository ente-io/ente
