name: Sync crowdin translation

on:
  push:
    paths: # run action automatically when en/translation.json file is changed
      - 'apps/photos/public/locales/en/translation.json'
    branches: [ main ]
  schedule:
    - cron: '0 */24 * * *' # Every 24 hours - https://crontab.guru/#0_*/12_*_*_*
  workflow_dispatch: # for manually running the action

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: crowdin action
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: true
          download_translations: true
          localization_branch_name: l10n_translations
          create_pull_request: true
          skip_untranslated_strings: true
          pull_request_title: 'New Translations'
          pull_request_body: 'New translations via [Crowdin GH Action](https://github.com/crowdin/github-action)'
          pull_request_base_branch_name: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
